//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriWinDirMover.Properties
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TriWinDirMover.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error
        {
            get
            {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TriWinDirMover.
        /// </summary>
        internal static string MainForm
        {
            get
            {
                return ResourceManager.GetString("MainForm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to At least one of the following commands failed:
        ///
        ///{0}
        ///.
        /// </summary>
        internal static string MainFormCommandsFailed
        {
            get
            {
                return ResourceManager.GetString("MainFormCommandsFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string MainFormItemsIsDisabled
        {
            get
            {
                return ResourceManager.GetString("MainFormItemsIsDisabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string MainFormItemsIsSymLink
        {
            get
            {
                return ResourceManager.GetString("MainFormItemsIsSymLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string MainFormItemsName
        {
            get
            {
                return ResourceManager.GetString("MainFormItemsName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string MainFormItemsPath
        {
            get
            {
                return ResourceManager.GetString("MainFormItemsPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string MainFormItemsSize
        {
            get
            {
                return ResourceManager.GetString("MainFormItemsSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string MainFormItemsTarget
        {
            get
            {
                return ResourceManager.GetString("MainFormItemsTarget", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to run process:
        ///
        ///{0}.
        /// </summary>
        internal static string MainFormProcessExecutionFailed
        {
            get
            {
                return ResourceManager.GetString("MainFormProcessExecutionFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string MainFormRefresh
        {
            get
            {
                return ResourceManager.GetString("MainFormRefresh", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string MainFormRunProcessMessageCaption
        {
            get
            {
                return ResourceManager.GetString("MainFormRunProcessMessageCaption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you really want to execute the following commands?
        ///
        ///{0}.
        /// </summary>
        internal static string MainFormRunProcessMessageConfirm
        {
            get
            {
                return ResourceManager.GetString("MainFormRunProcessMessageConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MainFormSettings
        {
            get
            {
                return ResourceManager.GetString("MainFormSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsForm
        {
            get
            {
                return ResourceManager.GetString("SettingsForm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string SettingsFormDirectorySets
        {
            get
            {
                return ResourceManager.GetString("SettingsFormDirectorySets", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string SettingsFormDirectorySetsSource
        {
            get
            {
                return ResourceManager.GetString("SettingsFormDirectorySetsSource", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string SettingsFormDirectorySetsTarget
        {
            get
            {
                return ResourceManager.GetString("SettingsFormDirectorySetsTarget", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string SettingsFormFlags
        {
            get
            {
                return ResourceManager.GetString("SettingsFormFlags", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Keep CMD Window Open.
        /// </summary>
        internal static string SettingsFormKeepCmdOpen
        {
            get
            {
                return ResourceManager.GetString("SettingsFormKeepCmdOpen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Startup Commands.
        /// </summary>
        internal static string SettingsFormPreCommands
        {
            get
            {
                return ResourceManager.GetString("SettingsFormPreCommands", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        internal static string SettingsFormPreCommandsCommand
        {
            get
            {
                return ResourceManager.GetString("SettingsFormPreCommandsCommand", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run as Administrator.
        /// </summary>
        internal static string SettingsFormRunAsAdmin
        {
            get
            {
                return ResourceManager.GetString("SettingsFormRunAsAdmin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run Startup Commands as Administrator.
        /// </summary>
        internal static string SettingsFormRunPreCommandsAsAdmin
        {
            get
            {
                return ResourceManager.GetString("SettingsFormRunPreCommandsAsAdmin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SettingsFormSave
        {
            get
            {
                return ResourceManager.GetString("SettingsFormSave", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Display Ignore.
        /// </summary>
        internal static string SettingsFormShowIsDisabled
        {
            get
            {
                return ResourceManager.GetString("SettingsFormShowIsDisabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Display Sizes.
        /// </summary>
        internal static string SettingsFormSizes
        {
            get
            {
                return ResourceManager.GetString("SettingsFormSizes", resourceCulture);
            }
        }
    }
}
